const swaggerAutogen = require('swagger-autogen')()


const doc = {
    info: {
        version: "1.0.0",
        title: "ToDo List Urbis API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "User",
            "description": "Endpoints of User"
        },
        {
            "name": "Task",
            "description": "Endpoints of Task"
        }
    ],
    securityDefinitions: {
        api_key: {
            type: "apiKey",
            name: "api_key",
            in: "header"
        },
        petstore_auth: {
            type: "oauth2",
            authorizationUrl: "https://petstore.swagger.io/oauth/authorize",
            flow: "implicit",
            scopes: {
                read_pets: "read your pets",
                write_pets: "modify pets in your account"
            }
        }
    },
    definitions: {
        Task: {
            $id: 0, 
            $name: 'Eat a blueberry pie',
            concluded: false,
            $id_user: 0 
        },
        User: {
            $id: 0,
            $name: "Jhon Doe",
            $email: "jhon_doe@hotmail.com",
            $password: "jhondoedetona"
        },

    }
}

const outputFile = './swagger_output.json'
const endpointsFiles = ['./src/Routes/User.js','./src/Routes/Task.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./index')           // Your project's root file
})
